# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Legosignoj
#define bookmarks_heading Legosignoj

#define bookmarks_toolbarfolder Dosierujo de la ilaro de legosignoj
#define bookmarks_toolbarfolder_description Aldonu legosignojn al tiu ĉi dosierujo por vidi ilin montritaj en la ilaro de legosignoj

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/icecat/central/
#define getting_started Unuaj paŝoj

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://en-US.www.mozilla.com/en-US/icecat/help/
#define icecat_help Helpo kaj gvidado

# LOCALIZATION NOTE (icecat_customize):
# link title for http://en-US.www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Agordi IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://en-US.www.mozilla.com/en-US/firefox.community/
#define firefox.community Partopreni

# LOCALIZATION NOTE (icecat_about):
# link title for http://en-US.www.mozilla.com/en-US/about/
#define icecat_about Pri ni

#unfilter emptyLines
