#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Segnalibri
#define bookmarks_heading Segnalibri

#define bookmarks_toolbarfolder Cartella della Barra dei segnalibri
#define bookmarks_toolbarfolder_description Aggiungere un segnalibro a questa cartella per vederlo nella barra dei segnalibri

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/icecat/central/
#define getting_started Come iniziare

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/en-US/icecat/help/
#define icecat_help Aiuto e guide

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Personalizza IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/en-US/firefox.community/
#define firefox.community Collabora con noi

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/en-US/icecat/about/
#define icecat_about Informazioni

#unfilter emptyLines
