# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Kirjanmerkit
#define bookmarks_heading Kirjanmerkit

#define bookmarks_toolbarfolder Kirjanmerkkipalkin kirjanmerkit
#define bookmarks_toolbarfolder_description Tässä kansiossa olevat ja tänne lisättävät kirjanmerkit ovat Kirjanmerkkipalkissa

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/icecat/central/
#define getting_started Aloitussivu

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for https://www.mozilla.org/en-US/icecat/help/
#define icecat_help Ohje ja oppaat

# LOCALIZATION NOTE (icecat_customize):
# link title for https://www.mozilla.org/en-US/icecat/customize/
#define icecat_customize Muokkaa IceCatia

# LOCALIZATION NOTE (firefox.community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox.community Osallistu projektiin

# LOCALIZATION NOTE (icecat_about):
# link title for https://www.mozilla.org/en-US/about/
#define icecat_about Tietoja Mozillasta

#unfilter emptyLines
