# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Lesezeichen
#define bookmarks_heading Lesezeichen

#define bookmarks_toolbarfolder Lesezeichen-Symbolleiste
#define bookmarks_toolbarfolder_description Lesezeichen, die Sie in diesem Ordner ablegen, werden in der Lesezeichen-Symbolleiste angezeigt.

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/icecat/central/
#define getting_started Erste Schritte

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for https://www.mozilla.org/en-US/icecat/help/
#define icecat_help Hilfe und Anleitungen

# LOCALIZATION NOTE (icecat_customize):
# link title for https://www.mozilla.org/en-US/icecat/customize/
#define icecat_customize IceCat anpassen

# LOCALIZATION NOTE (firefox.community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox.community Machen Sie mit

# LOCALIZATION NOTE (icecat_about):
# link title for https://www.mozilla.org/en-US/about/
#define icecat_about Über uns

#unfilter emptyLines
