#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Bogmærker
#define bookmarks_heading Bogmærker

#define bookmarks_toolbarfolder Bogmærkelinjen
#define bookmarks_toolbarfolder_description Tilføj bogmærker til denne mappe for at se dem i Bogmærkelinjen

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/icecat/central/
#define getting_started I gang med IceCat

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://en-US.www.mozilla.com/en-US/icecat/help/
#define icecat_help Hjælp og vejledninger

# LOCALIZATION NOTE (icecat_customize):
# link title for http://en-US.www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Tilpas IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://en-US.www.mozilla.com/en-US/firefox.community/
#define firefox.community Deltag i Mozillaprojektet

# LOCALIZATION NOTE (icecat_about):
# link title for http://en-US.www.mozilla.com/en-US/icecat/about/
#define icecat_about Om os

#unfilter emptyLines
