# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title পত্ৰচিহ্নসমূহ


#define bookmarks_heading পত্ৰচিহ্নসমূহ


#define bookmarks_toolbarfolder পত্ৰচিহ্নসমূহ টুলবাৰৰ ফোল্ডাৰ


#define bookmarks_toolbarfolder_description পত্ৰচিহ্নসমূহক পত্ৰচিহ্ন টুলবাৰত চাবলে এই ফোল্ডাৰত যোগ কৰক


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started আৰম্ভণি


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading GNU IceCat


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help সহায় আৰু শিক্ষা


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize IceCat স্বনিৰ্বাচন কৰক


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community জড়িত হওক


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about আমাৰ বিষয়ে


#unfilter emptyLines
