# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title မှတ်သားချက်များ


#define bookmarks_heading မှတ်သား လိပ်စာများ


#define bookmarks_toolbarfolder မှတ်သားလိပ်စာ အစုဖိုင်


#define bookmarks_toolbarfolder_description မှတ်သားလိပ်စာများအား မှတ်သားလိပ်စာဘားတန်းမှာပေါ်စေရန် ဤဖိုင်ထဲသို့ထည့်ပါ။


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started စတင်အသုံးပြုခြင်း


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading မော်ဇီလာမီးမြေခွေး


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help အကူအညီများနှင့်ကျူတိုရီရယ်များ


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize မီးမြေးခွေးအားပြုပြင်သုံးစွဲမည်


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community ဝင်ရောက်လှူပ်ရှားမည်။


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about ကျွန်ုပ်တို့အကြောင်း


#unfilter emptyLines
