# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Blêdwizers
#define bookmarks_heading Blêdwizers

#define bookmarks_toolbarfolder Map Blêdwizerarkbalke
#define bookmarks_toolbarfolder_description Foegje blêdwizers ta oan dizze map om se op de blêdwizerarkbalke wer te jaan

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/icecat/central/
#define getting_started Starte

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/en-US/icecat/help/
#define icecat_help Help en útlis

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/en-US/icecat/customize/
#define icecat_customize IceCat oanpasse

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/en-US/firefox.community/
#define firefox.community Meiwurkje

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/en-US/icecat/about/
#define icecat_about Oer Mozilla

#unfilter emptyLines
