# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Järjehoidjad
#define bookmarks_heading Järjehoidjad

#define bookmarks_toolbarfolder Järjehoidjariba kaust
#define bookmarks_toolbarfolder_description Lisa järjehoidjad sellesse kausta, kui soovid neid näha järjehoidjaribal

# LOCALIZATION NOTE (getting_started):
# link title for http://et.www.mozilla.com/et/icecat/central/
#define getting_started Alustamisjuhend

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://en-US.www.mozilla.com/en-US/icecat/help/
#define icecat_help Abi ja juhendid

# LOCALIZATION NOTE (icecat_customize):
# link title for http://en-US.www.mozilla.com/en-US/icecat/customize/
#define icecat_customize IceCati kohandamine

# LOCALIZATION NOTE (firefox.community):
# link title for http://en-US.www.mozilla.com/en-US/firefox.community/
#define firefox.community Aita kaasa

# LOCALIZATION NOTE (icecat_about):
# link title for http://en-US.www.mozilla.com/en-US/icecat/about/
#define icecat_about Meist

#unfilter emptyLines
