# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Закладки
#define bookmarks_heading Закладки

#define bookmarks_toolbarfolder Папка панели закладок
#define bookmarks_toolbarfolder_description Добавьте закладки в эту папку, чтобы увидеть их на панели закладок

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/ru/icecat/central/
#define getting_started Начальная страница

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/ru/icecat/help/
#define icecat_help Справка и руководства

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/ru/icecat/customize/
#define icecat_customize Настройка IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/ru/firefox.community/
#define firefox.community Присоединяйтесь к сообществу

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/ru/icecat/about/
#define icecat_about О нас

#unfilter emptyLines
