# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ओळखचिन्हे


#define bookmarks_heading ओळखचिन्हे


#define bookmarks_toolbarfolder ओळखचिन्हे साधनपट्टी फोल्डर


#define bookmarks_toolbarfolder_description ओळखचिन्हे साधनपट्टीवर दाखवण्यासाठी या फोल्डरवर ओळखचिन्हे समाविष्ट करा


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started सुरू करा


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading GNU IceCat


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help मदत व ट्यूटोरिअल्स्


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize IceCat पसंतीचे करा


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community सामिल व्हा


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about आमच्या विषयी


#unfilter emptyLines
