#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Zakładki
#define bookmarks_heading Zakładki

#define bookmarks_toolbarfolder Folder zakładek osobistych
#define bookmarks_toolbarfolder_description Zakładki umieszczone w tym folderze będą widoczne na pasku zakładek.

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/icecat/central/
#define getting_started Pierwsze kroki

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/en-US/icecat/help/
#define icecat_help Pomoc

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Dostosuj Firefoksa

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/en-US/firefox.community/
#define firefox.community Dołącz do nas

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/en-US/icecat/about/
#define icecat_about O Mozilli

#unfilter emptyLines
