# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Záložky
#define bookmarks_heading Záložky

#define bookmarks_toolbarfolder Složka lišty záložek
#define bookmarks_toolbarfolder_description Pro zobrazení záložky v liště záložek stačí přidat záložku do této složky

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/icecat/central/
#define getting_started Jak začít

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://en-US.www.mozilla.com/en-US/icecat/help/
#define icecat_help Nápověda a návody

# LOCALIZATION NOTE (icecat_customize):
# link title for http://en-US.www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Přizpůsobení IceCatu

# LOCALIZATION NOTE (firefox.community):
# link title for http://en-US.www.mozilla.com/en-US/firefox.community/
#define firefox.community Zapojte se

# LOCALIZATION NOTE (icecat_about):
# link title for http://en-US.www.mozilla.com/en-US/icecat/about/
#define icecat_about O nás

#unfilter emptyLines
