# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title બુકમાર્ક


#define bookmarks_heading બુકમાર્ક


#define bookmarks_toolbarfolder બુકમાર્ક સાધનો ફોલ્ડર


#define bookmarks_toolbarfolder_description બુકમાર્ક સાધનપટ્ટી પર જોવા માટે આ ફોલ્ડરમાં બુકમાર્ક ઉમેરો


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started શરૂ કરો


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading મોઝિલ્લા ફાયરફોક્સ


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help મદદ અને માર્ગદર્શિકાઓ


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize ફાયરફોક્સ વૈવિધ્યપૂર્ણ બનાવો


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community જોડાઇ જાવ


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about અમારા વિશે


#unfilter emptyLines
