# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Əlfəcinlər


#define bookmarks_heading Əlfəcinlər


#define bookmarks_toolbarfolder Əlfəcin Alət Sətiri Qovluğu


#define bookmarks_toolbarfolder_description Əlfəcinlər Çubuğunda görmək istədiyiniz əlfəcinləri bu qovluğa əlavə edin


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started İlk addım


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading GNU IceCat


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help Kömək və Öyrədicilər


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize IceCatu Fərdiləşdirin


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community Kömək edin


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about Haqqımızda


#unfilter emptyLines
