# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title पुस्तकचिह्न


#define bookmarks_heading पुस्तकचिह्न


#define bookmarks_toolbarfolder पुस्तकचिह्न अओजारपट्टी फोल्डर


#define bookmarks_toolbarfolder_description पुस्तचिह्न टूलबार मे देखाइ देबाक लेल एहि फोल्डर मे पुस्तचिह्न केँ जोड़ू


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started आरंभ करू


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading GNU IceCat


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help मदति आओर ट्यूटोरियल


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize फॉयरफॉक्स पसंदीदा करू


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community सामिल होउ


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about हमरा संबंध मे


#unfilter emptyLines
