# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ഓര്‍മ്മക്കുറിപ്പുകള്‍


#define bookmarks_heading ഓര്‍മ്മക്കുറിപ്പുകള്‍


#define bookmarks_toolbarfolder ഓര്‍മ്മക്കുറിപ്പുകള്‍ക്കുള്ള ടൂള്‍ബാര്‍ ഫോള്‍ഡര്‍


#define bookmarks_toolbarfolder_description ഓര്‍മ്മക്കറിപ്പുകളുടെ ടൂള്‍ബാറില്‍ പ്രദര്‍ശിപ്പിയ്ക്കുന്നതിനായി ഈ ഫോള്‍ഡര്‍ ഓര്‍മ്മക്കുറിപ്പുകളായി ചേര്‍ക്കുക


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started ഉപയോഗിച്ചു് തുടങ്ങുക


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading മോസില്ലാ ഫയര്‍ഫോക്സ്


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help സഹായങ്ങള്‍


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize ഫയല്‍ഫോക്സ് യഥേഷ്ടമാക്കുക


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community പങ്ക് ചേരൂ


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about ഞങ്ങളെപ്പറ്റി


#unfilter emptyLines
