# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ఇష్టాంశాలు


#define bookmarks_heading ఇష్టాంశాలు


#define bookmarks_toolbarfolder ఇష్టాంశముల సాధనములపట్టీ సంచయం


#define bookmarks_toolbarfolder_description ఇష్టాంశముల సాధనపట్టీ నందు వాటిని చూడుటకు యిష్టాంశములను యీ సంచయంకు జతచేయి


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started ప్రారంభించి నేర్చుకోండి


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading మొజిల్లా ఫైర్‌ఫాక్స్


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help సహాయం మరియు బోధనలు


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize ఫైర్‌ఫాక్సును ఇచ్ఛానుసారం మలచు


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community పాలుపంచుకోండి


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about మా గురించి


#unfilter emptyLines
