# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ଚିହ୍ନିତ ସ୍ଥାନ


#define bookmarks_heading ଚିହ୍ନିତ ସ୍ଥାନ


#define bookmarks_toolbarfolder ଚିହ୍ନିତ ସ୍ଥାନଗୁଡ଼ିକର ସାଧନପଟି ଫୋଲଡର


#define bookmarks_toolbarfolder_description ଚିହ୍ନିତ ସ୍ଥାନ ସାଧନପଟିରେ ଦର୍ଶାଇବା ପାଇଁ ଚିହ୍ନିତ ସ୍ଥାନଗୁଡ଼ିକୁ ଏହି ଫୋଲଡରରେ ଯୋଗକରନ୍ତୁ


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started ଆରମ୍ଭ କରୁଅଛି


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading GNU IceCat


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help ସହାୟତା ଏବଂ ଶିକ୍ଷଣ ବସ୍ତୁ


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize IceCat କୁ ଇଚ୍ଛାରୂପଣ କରନ୍ତୁ


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community ଅଂଶ ଗ୍ରହଣ କରନ୍ତୁ


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about ଆମ ବିଷୟରେ


#unfilter emptyLines
