#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Faqerojtës
#define bookmarks_heading Faqerojtës

#define bookmarks_toolbarfolder Dosje Paneli Faqerojtësish
#define bookmarks_toolbarfolder_description Shtoni faqerojtës te kjo dosje që t'i shihni ata të shfaqen te Paneli i Faqerojtësve

# LOCALIZATION NOTE (getting_started):
# link title for http://en-US.www.mozilla.com/en-US/icecat/central/
#define getting_started Si T'ia Fillohet

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://en-US.www.mozilla.com/en-US/icecat/help/
#define icecat_help Ndihmë dhe Përkujdesore

# LOCALIZATION NOTE (icecat_customize):
# link title for http://en-US.www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Personalizojeni IceCat-in

# LOCALIZATION NOTE (firefox.community):
# link title for http://en-US.www.mozilla.com/en-US/firefox.community/
#define firefox.community Përfshihuni

# LOCALIZATION NOTE (icecat_about):
# link title for http://en-US.www.mozilla.com/en-US/icecat/about/
#define icecat_about Rreth Nesh

#unfilter emptyLines
