#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Marque-pages
#define bookmarks_heading Marque-pages

#define bookmarks_toolbarfolder Barre personnelle
#define bookmarks_toolbarfolder_description Ajoutez des marque-pages dans ce dossier pour les voir apparaître sur votre barre personnelle

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/icecat/central/
#define getting_started Débuter avec IceCat

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/en-US/icecat/help/
#define icecat_help Aide et didacticiels

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Personnaliser IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/en-US/firefox.community/
#define firefox.community Contribuer

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/en-US/icecat/about/
#define icecat_about À propos de Mozilla

#unfilter emptyLines
