# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Bladwijzers
#define bookmarks_heading Bladwijzers

#define bookmarks_toolbarfolder Map Bladwijzerwerkbalk
#define bookmarks_toolbarfolder_description Voeg bladwijzers aan deze map toe om ze op de bladwijzerwerkbalk weer te geven

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/icecat/central/
#define getting_started Aan de slag

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for https://www.mozilla.org/en-US/icecat/help/
#define icecat_help Hulp en handleidingen

# LOCALIZATION NOTE (icecat_customize):
# link title for https://www.mozilla.org/en-US/icecat/customize/
#define icecat_customize IceCat aanpassen

# LOCALIZATION NOTE (firefox.community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox.community Meewerken

# LOCALIZATION NOTE (icecat_about):
# link title for https://www.mozilla.org/en-US/about/
#define icecat_about Over Mozilla

#unfilter emptyLines
