# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Закладкі
#define bookmarks_heading Закладкі

#define bookmarks_toolbarfolder Папка прыладапаліца закладак
#define bookmarks_toolbarfolder_description Дадавайце закладкі ў гэтую папку, каб пабачыць іх на прыладапаліцы закладак.

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/icecat/central/
#define getting_started У пачатку

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for https://www.mozilla.org/en-US/icecat/help/
#define icecat_help Даведка і дапаможнікі

# LOCALIZATION NOTE (icecat_customize):
# link title for https://www.mozilla.org/en-US/icecat/customize/
#define icecat_customize Уладкаванне IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for https://www.mozilla.org/en-US/contribute/
#define firefox.community Уцягвайцеся

# LOCALIZATION NOTE (icecat_about):
# link title for https://www.mozilla.org/en-US/about/
#define icecat_about Пра нас

# LOCALIZATION NOTE (icecat_feedback):
# link title for browser feedback page
# currently used by Metro only: https://input.mozilla.org/feedback/metroicecat
#define icecat_feedback Даць водгук

#unfilter emptyLines
