#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

# LOCALIZATION NOTE: Some of these URLs are currently 404s, but should be coming
# online shortly.

# LOCALIZATION NOTE (bookmarks_title):
# title for the folder that will contains the default bookmarks
#define bookmarks_title Mobile

# LOCALIZATION NOTE (bookmarks_aboutBrowser):
# link title for about:icecatmobile
#define bookmarks_aboutBrowser IceCat: તમારા બ્રાઉઝર વિશે

# LOCALIZATION NOTE (bookmarks_addons):
# link title for https://directory.fsf.org/wiki/GNU_IceCat
#define bookmarks_addons IceCat: ઍડ-ઓન વડે વૈવિધ્ય બનાવો

# LOCALIZATION NOTE (bookmarks_support):
# link title for https://libreplanet.org/wiki/Group:IceCat/icecat-help
#define bookmarks_support IceCat: આધાર

# LOCALIZATION NOTE (bookmarks_marketplace):
# link title for https://f-droid.org/repository/browse
#define bookmarks_marketplace IceCat બજાર

#unfilter emptyLines
