#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're 
# live.

#define bookmarks_title Marcadores
#define bookmarks_heading Marcadores

#define bookmarks_toolbarfolder Carpeta de barra de marcadores
#define bookmarks_toolbarfolder_description Agregue marcadores a esta carpeta para verlos en la barra de marcadores

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/icecat/central/
#define getting_started Primeros pasos

# LOCALIZATION NOTE (icecat_heading):
# IceCat links folder name
#define icecat_heading GNU IceCat

# LOCALIZATION NOTE (icecat_help):
# link title for http://www.mozilla.com/en-US/icecat/help/
#define icecat_help Ayuda y tutoriales

# LOCALIZATION NOTE (icecat_customize):
# link title for http://www.mozilla.com/en-US/icecat/customize/
#define icecat_customize Personalizar IceCat

# LOCALIZATION NOTE (firefox.community):
# link title for http://www.mozilla.com/en-US/firefox.community/
#define firefox.community Invol&#250;crese

# LOCALIZATION NOTE (icecat_about):
# link title for http://www.mozilla.com/en-US/icecat/about/
#define icecat_about Acerca de nosotros

#unfilter emptyLines
