# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title புத்தகக்குறிகள்


#define bookmarks_heading புத்தகக்குறிகள்


#define bookmarks_toolbarfolder புத்தகக்குறிகளுக்கான கருவிப்பட்டி அடைவு


#define bookmarks_toolbarfolder_description இந்த கோப்புறையில் புத்தகக்குறிகள் சேர்ப்பு அவைகளின் புத்தகக்குறிகளுக்கான கருவிப்பட்டையில் காட்டப்படும்


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/icecat/central/


#define getting_started துவங்குதல்


# LOCALIZATION NOTE (icecat_heading):


# IceCat links folder name


#define icecat_heading மோசில்லா பயர்பாக்ஸ்


# LOCALIZATION NOTE (icecat_help):


# link title for https://www.mozilla.org/en-US/icecat/help/


#define icecat_help உதவி மற்றும் பயிற்சிகள்


# LOCALIZATION NOTE (icecat_customize):


# link title for https://www.mozilla.org/en-US/icecat/customize/


#define icecat_customize icecat தனிப்பயனாக்கம்\u0020


# LOCALIZATION NOTE (firefox.community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox.community எங்களுடன் ஈடுபட


# LOCALIZATION NOTE (icecat_about):


# link title for https://www.mozilla.org/en-US/about/


#define icecat_about எங்களை பற்றி


#unfilter emptyLines
